### PR TITLE
fix: short watchlist scraping

### PR DESCRIPTION
**Pull request by BeSweets**
If a user's watchlist is 0 < n < 5, placeholder posters will be added to pad out the first 5. These placeholders break the scrape.

### CODE REVIEW

**Comment by BeSweets** [comment]
Small change, if a watchlist doesn't exist I'd argue the length should be 0, not None

**Comment by fastfingertips** [comment]
> If a user's watchlist is 0 < n < 5, placeholder posters will be added to pad out the first 5. These placeholders break the scrape.

Yes, you're right. Just changing this line is enough, edit the code then I'll merge it later.
```python
# watchlist_items = section_watclist.find_all("li")
watchlist_items = section_watchlist.find_all("li", {"class": ["film-poster"]})
```
> Small change, if a watchlist doesn't exist I'd argue the length should be 0, not None

Regarding defaulting to 0, it doesn't make sense to me to default to 0 for something that doesn't exist.

**Comment by BeSweets** [comment]
> Yes, you're right. Just changing this line is enough, edit the code then I'll merge it later.

Good call. Fixed a typo in the above line, too. Much cleaner, thanks.

>  > Small change, if a watchlist doesn't exist I'd argue the length should be 0, not None
> 
> Regarding defaulting to 0, it doesn't make sense to me to default to 0 for something that doesn't exist.

I'd argue the watchlist technically always exists, it's just empty. You can go to the watchlist page of a user you don't get a 404, it's a page with a header "{user} WANTS TO SEE 0 FILMS". And practically speaking, it seems more convenient for a length of a list to always be an int for comparisons.  I don't think there's a concept in letterboxd of a user with NO watchlist vs a user with 0 items in their watchlist that forces us to make the distinction by mixing types.

But I'll defer to you, I changed it back to None

**Comment by fastfingertips** [comment]
> I'd argue the watchlist technically always exists, it's just empty. You can go to the watchlist page of a user you don't get a 404, it's a page with a header "{user} WANTS TO SEE 0 FILMS". And practically speaking, it seems more convenient for a length of a list to always be an int for comparisons. I don't think there's a concept in letterboxd of a user with NO watchlist vs a user with 0 items in their watchlist that forces us to make the distinction by mixing types.

The section you mentioned only applies to HQ members. That's why I set it as None since HQ members don't have such a page. 

For basic members, we can successfully retrieve the watchlist length. For example:
```python
if "Watchlist" in link.text:
```
Here, we are searching for the text "Watchlist" in the navbar. If it's not found, the user is an HQ member; if it is found, they're a basic member. So, every member's profile must have this text.


Thank you for the changes.

**Comment by BeSweets** [comment]
Ah, that's a good point. Thanks!

**Pull request merged**
